ALTER TABLE `municipalities` RENAME TO `organization`;

ALTER TABLE `location` DROP FOREIGN KEY `FK714F9FB5F4E66D55`;

ALTER TABLE `location` CHANGE COLUMN `municipalityid` `organizationid` BIGINT(20) NOT NULL,
 DROP INDEX `FK714F9FB5F4E66D55`,
 ADD INDEX `FK714F9FB5F4E66D55` USING BTREE(`organizationid`),
 ADD CONSTRAINT `FK714F9FB5F4E66D55` FOREIGN KEY `FK714F9FB5F4E66D55` (`organizationid`)
    REFERENCES `organization` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE `course` DROP FOREIGN KEY `FKAF42E01BF4E66D55`;

ALTER TABLE `course` CHANGE COLUMN `feemunicipal` `feeinternal` DOUBLE NOT NULL,
 CHANGE COLUMN `reservedmunicipal` `reservedinternal` INTEGER NOT NULL,
 CHANGE COLUMN `municipalityid` `organizationid` BIGINT(20) NOT NULL,
 DROP INDEX `FKAF42E01BF4E66D55`,
 ADD INDEX `FKAF42E01BF4E66D55` USING BTREE(`organizationid`),
 ADD CONSTRAINT `FKAF42E01BF4E66D55` FOREIGN KEY `FKAF42E01BF4E66D55` (`organizationid`)
    REFERENCES `organization` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;
	
ALTER TABLE `registration` DROP FOREIGN KEY `FKAF83E8B9F4E66D55`;

ALTER TABLE `registration` CHANGE COLUMN `municipalityid` `organizationid` BIGINT(20) NOT NULL,
 DROP INDEX `FKAF83E8B9F4E66D55`,
 ADD INDEX `FKAF83E8B9F4E66D55` USING BTREE(`organizationid`),
 ADD CONSTRAINT `FKAF83E8B9F4E66D55` FOREIGN KEY `FKAF83E8B9F4E66D55` (`organizationid`)
    REFERENCES `organization` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;